name: Create PR from rel-10 to main
on:
  push:
    branches:
      - rel-1.0
jobs:
  merge-main-with-rel-1-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset branch
        run: |
          git fetch origin rel-1.0:rel-1.0
          git reset --hard rel-1.0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-merge/rel-7-0/${{github.run_number}}
          title: Merge branch main with rel-1.0
          token: ${{ github.token }}